version: '3'

services:
  code-beautifier:
    build: .
    container_name: code-beautifier
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - EXPIRY_DAYS=7
      # Connection string for PostgreSQL - must be provided as environment variable
      - POSTGRES_URI=${POSTGRES_URI}
    # Uncomment the following lines if using persistence
    # volumes:
    #   - ./data:/data
    restart: unless-stopped 